services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/inventory?schema=public
      JWT_SECRET: supersecret
      PORT: 4000
      CORS_ORIGIN: http://192.168.1.195:8080
      UPLOAD_DIR: /tmp
      ALLOW_REGISTRATION: 'false'
      ADMIN_EMAIL: admin@local
      ADMIN_PASSWORD: admin
      ADMIN_NAME: Админ
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
