import { prisma } from '../db/prisma.js'

export async function seedWarehouse() {
  const count = await prisma.warehouseItem.count()
  if (count > 0) return
  await prisma.warehouseItem.createMany({ data: [
    {
      name: 'Маршрутизатор Mikrotik hEX S',
      category: 'Сеть',
      manufacturer: 'MikroTik',
      model: 'RB760iGS',
      serialNumber: 'MTK-A1B2C3',
      quantity: 3,
      unit: 'шт',
      dateReceived: new Date('2025-09-15'),
      supplier: 'ООО "ТехноСнаб"',
      status: 'in_stock',
      location: 'Склад-А/Стеллаж 1',
      note: 'Готовы к выдаче',
    },
    {
      name: 'Коммутатор Cisco SG250-26',
      category: 'Сеть',
      manufacturer: 'Cisco',
      model: 'SG250-26',
      quantity: 2,
      unit: 'шт',
      dateReceived: new Date('2025-10-01'),
      supplier: 'Поставщик "СетьПроф"',
      status: 'reserved',
      location: 'Склад-А/Стеллаж 2',
      note: 'Для проекта филиал-2',
    },
    {
      name: 'МФУ Brother DCP-L2520D',
      category: 'Печать',
      manufacturer: 'Brother',
      model: 'DCP-L2520D',
      serialNumber: 'BR-99887',
      quantity: 1,
      unit: 'шт',
      dateReceived: new Date('2025-08-20'),
      supplier: 'ООО "ОфисМаркет"',
      status: 'in_stock',
      location: 'Склад-Б/Полка 3',
    },
    {
      name: 'Набор клавиатура+мышь Logitech MK270',
      category: 'Периферия',
      manufacturer: 'Logitech',
      model: 'MK270',
      quantity: 5,
      unit: 'комплект',
      dateReceived: new Date('2025-10-05'),
      supplier: 'ООО "Комп-Снаб"',
      status: 'issued',
      location: 'Склад-Б/Полка 1',
      note: 'Часть выдана ИТ-отделу',
    },
    {
      name: 'SSD Kingston 512GB',
      category: 'Накопители',
      manufacturer: 'Kingston',
      model: 'A400 512GB',
      quantity: 10,
      unit: 'шт',
      dateReceived: new Date('2025-09-28'),
      supplier: 'ООО "ХардСтор"',
      status: 'in_stock',
      location: 'Склад-А/Ячейка 12',
    },
    {
      name: 'Блок питания 650W',
      category: 'Запчасти',
      quantity: 4,
      unit: 'шт',
      dateReceived: new Date('2025-10-10'),
      supplier: 'ИП Петров',
      status: 'reserved',
      location: 'Склад-А/Ячейка 7',
      note: 'Резерв для сборки ПК',
    },
    {
      name: 'Ноутбук Lenovo V15',
      category: 'Компьютеры',
      manufacturer: 'Lenovo',
      model: 'V15 G3',
      quantity: 2,
      unit: 'шт',
      dateReceived: new Date('2025-10-12'),
      supplier: 'ООО "ТехДистрибуция"',
      status: 'in_stock',
      location: 'Склад-Б/Полка 5',
    },
  ]})
}
